server:
  context-path: /vesselIoT
#
#vessel properties
#
vessel:
 vid: 413362260
 vids: vids.csv
 locations:
   fileName: locations.csv
 destinations:
   fileName: DE413362260.csv
 states:
   fileName: VS413362260.csv
 topic:
   delay: activiti/delay

#
#AWS properties
#
awsiot:
  keys: keys.csv
